//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSalesData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarSalesEntities : DbContext
    {
        public CarSalesEntities()
            : base("name=CarSalesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<ConstructeursVoiture> ConstructeursVoiture { get; set; }
        public virtual DbSet<ContratAchat> ContratAchat { get; set; }
        public virtual DbSet<Employe> Employe { get; set; }
        public virtual DbSet<Facture> Facture { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<Operation> Operation { get; set; }
        public virtual DbSet<Personne> Personne { get; set; }
        public virtual DbSet<Piece> Piece { get; set; }
        public virtual DbSet<Plein> Plein { get; set; }
        public virtual DbSet<TauxHoraire> TauxHoraire { get; set; }
        public virtual DbSet<Vehicule> Vehicule { get; set; }
        public virtual DbSet<VehiculeNeuf> VehiculeNeuf { get; set; }
        public virtual DbSet<VehiculeOccasion> VehiculeOccasion { get; set; }
    }
}
