//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSalesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public int IdEmploye { get; set; }
        public int IdVehicule { get; set; }
        public System.DateTime DateDebut { get; set; }
        public decimal PrixLocation { get; set; }
        public int Duree { get; set; }
    
        public virtual Professionnel Professionnel { get; set; }
        public virtual Personne Personne { get; set; }
        public virtual Vehicule Vehicule { get; set; }
    }
}
