//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSalesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Piece
    {
        public int Id { get; set; }
        public Nullable<int> IdOperation { get; set; }
        public string Description { get; set; }
        public decimal Prix { get; set; }
    
        public virtual Operation Operation { get; set; }
    }
}
